name: firenote_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  crypto: ^3.0.6
  json_annotation: ^4.9.0
  intl: ^0.20.1
  firebase_database: ^11.3.0
  flutter_staggered_grid_view: ^0.7.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
