// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcEbI3UdBa2uk52rn7OvANds1z-jKY-8U',
    appId: '1:491704670887:web:eed79cd16b1a8a3f9c5982',
    messagingSenderId: '491704670887',
    projectId: 'firenote-bf533',
    authDomain: 'firenote-bf533.firebaseapp.com',
    databaseURL: 'https://firenote-bf533-default-rtdb.firebaseio.com',
    storageBucket: 'firenote-bf533.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWrw0mRk8uTodM_f8fPCoqF0A31wGm9Bg',
    appId: '1:491704670887:android:7b8ac5007c5d1ab59c5982',
    messagingSenderId: '491704670887',
    projectId: 'firenote-bf533',
    databaseURL: 'https://firenote-bf533-default-rtdb.firebaseio.com',
    storageBucket: 'firenote-bf533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVjh-LhzYmmy-968zXrG2irlxj1RsszLY',
    appId: '1:491704670887:ios:b571bb25d3ecee6b9c5982',
    messagingSenderId: '491704670887',
    projectId: 'firenote-bf533',
    databaseURL: 'https://firenote-bf533-default-rtdb.firebaseio.com',
    storageBucket: 'firenote-bf533.firebasestorage.app',
    iosBundleId: 'com.example.firenote2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVjh-LhzYmmy-968zXrG2irlxj1RsszLY',
    appId: '1:491704670887:ios:b571bb25d3ecee6b9c5982',
    messagingSenderId: '491704670887',
    projectId: 'firenote-bf533',
    databaseURL: 'https://firenote-bf533-default-rtdb.firebaseio.com',
    storageBucket: 'firenote-bf533.firebasestorage.app',
    iosBundleId: 'com.example.firenote2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcEbI3UdBa2uk52rn7OvANds1z-jKY-8U',
    appId: '1:491704670887:web:706389be1e795eed9c5982',
    messagingSenderId: '491704670887',
    projectId: 'firenote-bf533',
    authDomain: 'firenote-bf533.firebaseapp.com',
    databaseURL: 'https://firenote-bf533-default-rtdb.firebaseio.com',
    storageBucket: 'firenote-bf533.firebasestorage.app',
  );
}
